#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt update
sudo apt install nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
